version: '3'
services:
  web:
    build: ./
    ports:
      - "85:80"
    depends_on:
      - db
    expose:
      - 9010
    volumes:
      - ./:/var/www/html/
      - ./local/php.ini:/usr/local/etc/php/php.ini
      - ./local/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - apireact_network

  db:
    image: mysql
    ports:
      - "3389:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apireact_db
      MYSQL_USER: 123456
      MYSQL_PASSWORD: badr
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - apireact_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - apireact_network

networks:
  apireact_network:
    driver: bridge
